package com.safe.space.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Crisis Alert entity.
 *
 * Persisted alerts generated by the intelligent monitoring engine.
 * Unlike the old on-the-fly alert computation, these are stored for
 * audit trails, acknowledgment tracking, and pattern analysis.
 *
 * Alert sources:
 *   - CRISIS_POST        → Flagged rant board post with crisis keywords
 *   - HIGH_ENERGY_POST   → Post with energy score >= 8 (not flagged)
 *   - CRISIS_CHAT        → Chat session with crisis flag
 *   - REPEAT_CRISIS      → Same pseudonym flagged multiple times (pattern)
 *   - ENERGY_SPIKE       → Sudden energy increase for a user
 *   - SYSTEM_EVENT       → System-level events (lockouts, bulk imports, etc.)
 *
 * Lifecycle: ACTIVE → ACKNOWLEDGED → RESOLVED / ESCALATED
 */
@Entity
@Table(name = "crisis_alerts", indexes = {
        @Index(name = "idx_alert_status", columnList = "status"),
        @Index(name = "idx_alert_severity", columnList = "severity"),
        @Index(name = "idx_alert_created", columnList = "createdAt"),
        @Index(name = "idx_alert_type", columnList = "alertType")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CrisisAlert {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Unique public alert identifier. */
    @Column(nullable = false, unique = true, length = 50)
    private String alertId;

    /**
     * Alert source type:
     *   CRISIS_POST, HIGH_ENERGY_POST, CRISIS_CHAT,
     *   REPEAT_CRISIS, ENERGY_SPIKE, SYSTEM_EVENT
     */
    @Column(nullable = false, length = 30)
    private String alertType;

    /**
     * Severity level: CRITICAL, HIGH, MODERATE, LOW, INFO
     */
    @Column(nullable = false, length = 20)
    private String severity;

    /**
     * Current alert status: ACTIVE, ACKNOWLEDGED, RESOLVED, ESCALATED
     */
    @Column(nullable = false, length = 20)
    @Builder.Default
    private String status = "ACTIVE";

    /** Reference ID linking to the source (postId, sessionId, username). */
    @Column(length = 100)
    private String referenceId;

    /** Source type for the reference: POST, CHAT, USER */
    @Column(length = 20)
    private String referenceType;

    /** Short title for the alert. */
    @Column(nullable = false, length = 200)
    private String title;

    /** Detailed message describing the alert. */
    @Column(nullable = false, length = 2000)
    private String message;

    /** Pseudonym of the user involved (if applicable). */
    @Column(length = 100)
    private String pseudonym;

    /** Emotion tag from the source. */
    @Column(length = 20)
    private String emotionTag;

    /** Energy score from the source. */
    private Integer energyScore;

    /** Crisis keywords detected (if applicable). */
    @Column(length = 1000)
    private String flaggedKeywords;

    /** Username of the professional who acknowledged this alert. */
    @Column(length = 50)
    private String acknowledgedBy;

    @Column
    private LocalDateTime acknowledgedAt;

    /** Username of the professional who resolved/escalated. */
    @Column(length = 50)
    private String resolvedBy;

    @Column
    private LocalDateTime resolvedAt;

    /** Resolution notes from the professional. */
    @Column(length = 2000)
    private String resolutionNotes;

    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        if (createdAt == null) createdAt = LocalDateTime.now();
    }
}
