package com.safe.space.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Tracks every auto-reply generated by the system.
 * Used for analytics, auditing, and measuring engagement
 * with different reply types across emotion/energy combinations.
 */
@Entity
@Table(name = "auto_reply_logs")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AutoReplyLog {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Link to the post that triggered this reply (nullable for preview/test calls). */
    @Column
    private String postId;

    @Column(nullable = false, length = 20)
    private String emotionTag;

    @Column(nullable = false)
    private int energyScore;

    /** The tier that was selected: "low", "mid", "high", or "crisis". */
    @Column(nullable = false, length = 10)
    private String tier;

    /** The rule that matched (e.g. "CRISIS_OVERRIDE", "HIGH_Sad", "MID_Anxious"). */
    @Column(nullable = false, length = 50)
    private String ruleMatched;

    /** The reply message that was sent. */
    @Column(nullable = false, length = 2000)
    private String replyMessage;

    /** Whether crisis keywords were detected in the post content. */
    @Column(nullable = false)
    private boolean crisisDetected;

    /** Number of suggested actions attached to this reply. */
    @Column(nullable = false)
    private int suggestedActionsCount;

    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
    }
}
